name: Build and Deploy Flutter Web

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: ["main"]

  # Manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install Flutter SDK (this will also install the Dart SDK bundled with Flutter)
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0' # Ensures Dart SDK >= 3.0.1 is used

    # Run Flutter Doctor to ensure proper setup
    - name: Run Flutter Doctor
      run: flutter doctor

    # Run Flutter Pub Get to install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build Flutter Web
    - name: Build Flutter Web
      run: flutter build web

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
